# Generated by Django 6.1.1 on 2026-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='naoaguentomais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uh', models.IntegerField(verbose_name='uashgbdj')),
            ],
        ),
    ]
