# Generated by Django 6.1.1 on 2026-09-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0002_naoaguentomais'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCardapio',
        ),
        migrations.DeleteModel(
            name='naoaguentomais',
        ),
    ]
