# Generated by Django 6.1.1 on 2026-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.CharField(choices=[('1', 'Sanduíches'), ('2', 'Salgados'), ('3', 'Bebidas')], max_length=100, verbose_name='Categoria'),
        ),
    ]
