# Generated by Django 6.1.1 on 2026-09-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0005_alter_itemcardapio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.CharField(choices=[(1, 'Sanduíches'), (2, 'Salgados'), (3, 'Bebidas')], max_length=100, verbose_name='Categoria'),
        ),
    ]
