# Generated by Django 6.1.1 on 2026-10-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0007_alter_itemcardapio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
