# Generated by Django 6.1.1 on 2026-10-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancheapp', '0008_itemcardapio_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='desc',
            field=models.CharField(default='', max_length=300, verbose_name='Descrição'),
        ),
    ]
